spring.application.name=demo

# Selects which profile-specific config file to load.
# application-dev.properties + application-dev.yml will be loaded alongside this file.
spring.profiles.active=${SPRING_PROFILE:dev}
